### ISSUE TITLE
extra text in list of sponsoring lawmakers

### ISSUE THREAD

**Issue by doughardy-ctnj** [mzagaja/ctnj-legislation#18]
Sponsors
b'Bocchino, Mike',
b'Lemar, Roland J.',
b'Miller, Patricia Billie',
b'Ferraro, Charles J.',
b"D'Agostino, Michael",
b"O'Dea, Tom",
b'Stallworth, Charlie L.',
b'Carney, Devin R.',
b'Porter, Robyn A.',
b'Adams, Terry B.',
b'Fleischmann, Andrew M.',
b'Hwang, Tony',

**Comment by mzagaja** [comment]
Fixed this a few weeks ago.
