### ISSUE TITLE
Bill duplication

### ISSUE THREAD

**Issue by doughardy-ctnj** [mzagaja/ctnj-legislation#19]
An Act Eliminating The Business Entity Tax is showing up twice.

https://bills.ctnewsjunkie.com/bills/2018hb-5017

https://bills.ctnewsjunkie.com/bills/2018hb-5010

**Comment by mzagaja** [comment]
If you look at the official bill pages you'll see that these are in fact two different bills with the same name introduced by two different legislators. So not an error.
