### ISSUE TITLE
Related Articles

### ISSUE THREAD

**Issue by doughardy-ctnj** [mzagaja/ctnj-legislation#22]
How did you set these google queries up for the related articles? 

https://bills.ctnewsjunkie.com/bills/2018sb-180

Seems like the word "contract" is probably drawing in lots of somewhat unrelated articles.

BTW, I'm chatting with Kyle about setting up feeds from the news site for specific bills and he's a little concerned about slowing everything down but we're talking about it.

**Comment by mzagaja** [comment]
It uses Google site search to search CTNJ using the bill title and populate the links dynamically. We can change it to use the bill number only but this will narrow the results significantly. Unless you want to manually mark related articles for hundreds of bills there isn't going to be a perfect way to do this so its just a matter of deciding the trade off between having some kind of results versus perfect results versus the amount of labor you want to throw at this.
